# Generated by Django 2.2.1 on 2019-05-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMGSched', '0002_auto_20190526_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='manager',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
