# Generated by Django 2.2.1 on 2019-06-12 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMGSched', '0004_auto_20190526_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=100)),
                ('posted_on', models.DateField()),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMGSched.Event')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMGSched.People')),
            ],
        ),
    ]
